services:
  docs:
    image: jagdhamb_trust_pune_local_docs
    container_name: jagdhamb_trust_pune_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./jagdhamb_trust_pune:/app/jagdhamb_trust_pune:z
    ports:
      - '9000:9000'
    command: /start-docs
