# Generated by Django 5.1.8 on 2025-04-12 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('expires_at', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Expired')], default=1)),
                ('type', models.CharField(choices=[('NORMAL', 'Normal'), ('REFRESH', 'Refresh')], default='NORMAL', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JWT',
            },
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A Pos'), ('A-', 'A Neg'), ('B+', 'B Pos'), ('B-', 'B Neg'), ('AB+', 'Ab Pos'), ('AB-', 'Ab Neg'), ('O+', 'O Pos'), ('O-', 'O Neg')], max_length=5, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F'), ('OTHER', 'Other')], max_length=10)),
                ('instrument', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.IntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
