# Generated by Django 5.1.8 on 2025-04-17 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jwt_userregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='instrument',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
    ]
