# Generated by Django 5.1.8 on 2025-04-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userregister_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='instrument',
            field=models.CharField(max_length=100),
        ),
    ]
