# Generated by Django 5.1.8 on 2025-04-19 13:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userregister_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='experience_pathak_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='experience_years',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='instrument',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
    ]
