# Generated by Django 5.1.8 on 2025-04-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_instrument_remove_userregister_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userinstruments'),
        ),
    ]
