# Generated by Django 5.1.8 on 2025-04-25 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userregister_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='userinstruments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregister'),
        ),
    ]
